-- REAP LIFE production schema for Supabase/Postgres.
create extension if not exists pgcrypto;
create type public.app_role as enum ('admin','editor','prayer_team','presenter','viewer');
create type public.publish_state as enum ('draft','review','published','archived');
create type public.prayer_request_state as enum ('new','review','assigned','prayed','follow_up','closed');
create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade,display_name text,role public.app_role not null default 'viewer',active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.master_messages (id text primary key,title text not null,scripture text,description text,body text,state public.publish_state not null default 'draft',speaker text,teaser_start_seconds numeric,teaser_end_seconds numeric,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.media_items (id text primary key,master_message_id text references public.master_messages(id) on delete set null,type text not null check(type in ('audio','video','visual_audio','image','document')),title text,storage_bucket text,storage_path text,public_url text,duration_seconds numeric,width integer,height integer,mime_type text,state public.publish_state not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.life_memos (id text primary key,master_message_id text references public.master_messages(id) on delete set null,title text not null,scripture text not null,reflection text,prayer text,state public.publish_state not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.prayer_programs (id text primary key,title text not null,description text,status public.publish_state not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.prayer_sessions (id uuid primary key default gen_random_uuid(),program_id text not null references public.prayer_programs(id) on delete cascade,day_number integer not null,title text not null,scripture text,teaching text,written_prayer text,audio_media_id text references public.media_items(id) on delete set null,video_media_id text references public.media_items(id) on delete set null,created_at timestamptz not null default now(),unique(program_id,day_number));
create table if not exists public.prayer_points (id uuid primary key default gen_random_uuid(),session_id uuid references public.prayer_sessions(id) on delete cascade,library_title text,text text not null,scripture text,sort_order integer not null default 0);
create table if not exists public.prayer_requests (id uuid primary key default gen_random_uuid(),title text,request_text text not null,state public.prayer_request_state not null default 'new',visibility text not null default 'private' check(visibility in ('private','prayer_team','community')),submitter_user_id uuid references auth.users(id) on delete set null,assigned_to uuid references auth.users(id) on delete set null,follow_up_needed boolean not null default false,expires_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.live_events (id uuid primary key default gen_random_uuid(),title text not null,description text,stream_url text,thumbnail_path text,starts_at timestamptz,ends_at timestamptz,state public.publish_state not null default 'draft',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.audit_logs (id bigint generated always as identity primary key,actor_id uuid references auth.users(id) on delete set null,action text not null,entity_type text,entity_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create index if not exists idx_master_messages_state on public.master_messages(state);
create index if not exists idx_media_master on public.media_items(master_message_id);
create index if not exists idx_prayer_requests_state on public.prayer_requests(state);
create index if not exists idx_prayer_requests_expires on public.prayer_requests(expires_at);
create index if not exists idx_live_events_starts on public.live_events(starts_at);
create or replace function public.current_role() returns public.app_role language sql stable security definer set search_path=public as $$ select role from public.profiles where id=auth.uid() and active=true limit 1; $$;
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select public.current_role() in ('admin','editor','prayer_team','presenter'); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,display_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'display_name',split_part(new.email,'@',1)),'viewer') on conflict(id) do nothing; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security;
alter table public.master_messages enable row level security;
alter table public.media_items enable row level security;
alter table public.life_memos enable row level security;
alter table public.prayer_programs enable row level security;
alter table public.prayer_sessions enable row level security;
alter table public.prayer_points enable row level security;
alter table public.prayer_requests enable row level security;
alter table public.live_events enable row level security;
alter table public.audit_logs enable row level security;
create policy "public read published messages" on public.master_messages for select using(state='published');
create policy "public read published media" on public.media_items for select using(state='published');
create policy "public read published memos" on public.life_memos for select using(state='published');
create policy "public read published programs" on public.prayer_programs for select using(status='published');
create policy "public read published sessions" on public.prayer_sessions for select using(exists(select 1 from public.prayer_programs p where p.id=program_id and p.status='published'));
create policy "public read published points" on public.prayer_points for select using(exists(select 1 from public.prayer_sessions s join public.prayer_programs p on p.id=s.program_id where s.id=session_id and p.status='published'));
create policy "public read live events" on public.live_events for select using(state='published');
create policy "staff manage messages" on public.master_messages for all using(public.is_staff()) with check(public.is_staff());
create policy "staff manage media" on public.media_items for all using(public.is_staff()) with check(public.is_staff());
create policy "staff manage memos" on public.life_memos for all using(public.is_staff()) with check(public.is_staff());
create policy "staff manage programs" on public.prayer_programs for all using(public.current_role() in ('admin','editor','prayer_team')) with check(public.current_role() in ('admin','editor','prayer_team'));
create policy "staff manage sessions" on public.prayer_sessions for all using(public.current_role() in ('admin','editor','prayer_team')) with check(public.current_role() in ('admin','editor','prayer_team'));
create policy "staff manage points" on public.prayer_points for all using(public.current_role() in ('admin','editor','prayer_team')) with check(public.current_role() in ('admin','editor','prayer_team'));
create policy "admins manage profiles" on public.profiles for all using(public.current_role()='admin') with check(public.current_role()='admin');
create policy "users read own profile" on public.profiles for select using(id=auth.uid());
create policy "authenticated submit prayer request" on public.prayer_requests for insert to authenticated with check(submitter_user_id=auth.uid() and visibility='private');
create policy "requester read own prayer request" on public.prayer_requests for select using(submitter_user_id=auth.uid());
create policy "prayer team manage requests" on public.prayer_requests for all using(public.current_role() in ('admin','prayer_team')) with check(public.current_role() in ('admin','prayer_team'));
create policy "admin read audit logs" on public.audit_logs for select using(public.current_role()='admin');
create policy "staff create audit logs" on public.audit_logs for insert to authenticated with check(actor_id=auth.uid() and public.is_staff());
insert into storage.buckets(id,name,public) values('reap-media','reap-media',false),('reap-images','reap-images',false),('reap-documents','reap-documents',false) on conflict(id) do update set public=false;
create policy "staff upload media" on storage.objects for insert to authenticated with check(bucket_id in ('reap-media','reap-images','reap-documents') and public.is_staff());
create policy "staff update media" on storage.objects for update to authenticated using(bucket_id in ('reap-media','reap-images','reap-documents') and public.is_staff()) with check(bucket_id in ('reap-media','reap-images','reap-documents') and public.is_staff());
create policy "staff delete media" on storage.objects for delete to authenticated using(bucket_id in ('reap-media','reap-images','reap-documents') and public.current_role() in ('admin','editor'));
